# The URL the site will be built for
base_url           = "https://example.com"
# The title of the website
title              = "John Q. Example's Blog"
# The description of the website
description        = "Sample website to demonstrate Sleek theme"

# Compile all SASS files in the sass directory
compile_sass       = true

# Build a search index in the project root
build_search_index = true

# Compress generated HTML
minify_html        = true

# Generate feeds for posts and/ortaxonomies
generate_feed      = false

# Default language for html and search functions
default_language   = "en"

# Default taxonomy lists
taxonomies         = [
  { name           = "tags", feed = true },
  # { name         = "categories", paginate_by = 5}
]

[search]
# Use JSON over JS for the search index file
index_format       = "elasticlunr_json"

[markdown]
# Perform syntax highlighting on code snippets
highlight_code     = true
# Use the following theme for highlights
highlight_theme    = "monokai"

[extra]
sleek_author       = "John Q. Example"
sleek_abbr         = "JQE"
sleek_quote        = "You get what you pay for!"

sleek_copyright    = "All rights reserved."
sleek_mathjax      = true

sleek_logo           = "images/globe-nord6.svg"
# sleek_icon         = ""
# sleek_logo         = "images/lambda-white.svg"
# sleek_image        = ""

sleek_navbar       = [
  { name           = "Home",       link = "/"},
  { name           = "Blog",       link = "/blog" },
  { name           = "Tags",       link = "/tags" },
  # { name         = "Categories", link ="/categories" },
  { name           = "About",      link  = "/about"}
]

sleek_pages        = [
  { name           = "twitter",    link = "https://twitter.com" },
  { name           = "github",     link = "https://github.com" },
  { name           = "email",      link = "mailto:author@domain.com" }
]

sleek_tags         = [
  { name           = "blog",       link = "/tags/blog" },
  { name           = "lorem",      link = "/tags/lorem" },
  { name           = "post",       link = "/tags/post" }
]

# sleek_menu       = []
