# The URL the site will be built for
base_url              = "https://sleek-4lj.pages.dev"
# The title of the website
title                 = "John Q. Example's Blog"
# The description of the website
description           = "Sample website to demonstrate Sleek theme"

# Compile all SASS files in the sass directory
compile_sass          = true

# Build a search index in the project root
build_search_index    = true

# Compress generated HTML
minify_html           = true

# Generate feeds for posts and/or taxonomies
generate_feed         = true

# The feed file name to use for syndication
feed_filename         = "atom.xml"
# Default language for html and search functions
default_language      = "en"

# Default taxonomy lists and settings
taxonomies            = [
  { name              = "tags", feed = true },
  { name              = "topics", feed = true },
  { name              = "keywords", feed = false }
]

[search]
# Use JSON over JS for the search index file
index_format          = "elasticlunr_json"

[markdown]
# Perform syntax highlighting on code snippets
highlight_code        = true
# Use the following theme for highlights
highlight_theme       = "nord"

[extra]
# The author of the website
sleek_author          = "John Q. Example"
# Alternate text for the logo image
sleek_abbr            = "JQE"
# displayed below title of website on homepage
sleek_quote           = "You get what you pay for!"
# website copyright statement
sleek_copyright       = "All rights reserved"
# todo: implement
sleek_mathjax         = false
# list of tags to display in the footer
sleek_footer_tags     = [
  "blog",
  "lorem",
  "post"
]

sleek_footer_topics   = []

sleek_topics_metadata = "topics/descriptions.json"

# sleek_search        = true
sleek_topics          = [
]

# path to the logo svg
sleek_logo            = "images/QQ-nord6.svg"

# menu items for the navbar
sleek_menu            = [
  { name              = "Home",       link = "/"},
  { name              = "Blog",       link = "/blog" },
  { name              = "Tags",       link = "/tags" },
  { name              = "Topics",     link = "/topics" },
  { name              = "About",      link = "/about"}
]

# website and pages linked on the homepage
sleek_pages           = [
  { name              = "twitter",    link = "https://twitter.com" },
  { name              = "github",     link = "https://github.com" },
  { name              = "linkedin",   link = "https:/linkedin.com" },
  { name              = "email",      link = "mailto:john@example.com" }
]
