# The URL the site will be built for
base_url           = "https://sleek-4lj.pages.dev"
# The title of the website
title              = "John Q. Example's Blog"
# The description of the website
description        = "Sample website to demonstrate Sleek theme"

# Compile all SASS files in the sass directory
compile_sass       = true

# Build a search index in the project root
build_search_index = true

# Compress generated HTML
minify_html        = true

# Generate feeds for posts and/or taxonomies
generate_feed      = true

# The feed file name to use for syndication
feed_filename      = "atom.xml"
# Default language for html and search functions
default_language   = "en"

# Default taxonomy lists and settings
taxonomies         = [
  { name           = "tags", feed = true },
  # { name         = "categories", paginate_by = 5}
]

[search]
# Use JSON over JS for the search index file
index_format       = "elasticlunr_json"

[markdown]
# Perform syntax highlighting on code snippets
highlight_code     = true
# Use the following theme for highlights
# highlight_theme    = "monokai"
highlight_theme    = "nord"

[extra]
# The author of the website
sleek_author       = "John Q. Example"
# Alternate text for the logo image
sleek_abbr         = "JQE"
# displayed below title of website on homepage
sleek_quote        = "You get what you pay for!"
# website copyright statement
sleek_copyright    = "All rights reserved"
# todo: implement
sleek_mathjax      = false
# whether to include selected tags at bottom of page
sleek_footer_tags  = true
# list of tags to display in the footer
sleek_tags         = [
  "blog",
  "lorem",
  "post"
]
# path to the logo svg
sleek_logo         = "images/Q-nord6.svg"

# menu items for the navbar
sleek_menu         = [
  { name           = "Home",       link = "/"},
  { name           = "Blog",       link = "/blog" },
  { name           = "Tags",       link = "/tags" },
  # { name         = "Categories", link ="/categories" },
  { name           = "About",      link  = "/about"}
]

# website and pages linked on the homepage
sleek_pages        = [
  { name           = "twitter",    link = "https://twitter.com/johnqe" },
  { name           = "github",     link = "https://github.com/johnqe" },
  { name           = "email",      link = "mailto:john@example.com" }
]

