# theme name: note the capitalization
name            = "Sleek"

# Theme description and tagline summary
description     = "A minimalistic theme a for personal website or blog"

# Theme license: see LICENSE file for details
license         = "MIT"

# Project Github repository
homepage        = "https://github.com/CarterLevinson/sleek"

# Sleek supports Zola Versions >= 0.17.0
min_version     = "0.17.0"

# Cloudflare Pages site URL
demo            = "https://sleek-4lj.pages.dev"

[author]
# My name
name            = "Carter S. Levinson"

# My blog
homepage        = "https://carterlevinson.net"

[extra]
# The author of the website
author          = "John Q. Example"

# website copyright statement
copyright       = "All rights reserved"

# static json containing large topic descriptions
topics_metadata = "topics/descriptions.json"

# list of tags to display in the footer
footer_tags     = [
  "blog",
  "lorem",
  "post",
  "first",
]

# menu links for the navbar menu
menu_links      = [
  { name        = "Home",       link = "/"},
  { name        = "Blog",       link = "/blog" },
  { name        = "Tags",       link = "/tags" },
  { name        = "Topics",     link = "/topics" },
  { name        = "About",      link = "/about"}
]

# path to the SVG logo
sleek_logo      = "images/QQ-nord6.svg"

# Alternate text for the logo image
sleek_abbr      = "JQE"

# displayed below title of website on homepage
sleek_quote     = "You get what you pay for!"

# website and pages linked on the homepage
sleek_pages     = [
  { name        = "twitter",    link = "https://twitter.com" },
  { name        = "github",     link = "https://github.com" },
  { name        = "linkedin",   link = "https:/linkedin.com" },
  { name        = "email",      link = "mailto:john@example.com" }
]
