name            = "Sleek"
description     = "A minimalistic theme a for personal website or blog"
license         = "MIT"
homepage        = "https://github.com/CarterLevo/Sleek"

# test other versions?
min_version     = "0.17.0"

# use a Github pages site to host theme?
demo            = "https://sleek-4lj.pages.dev/"

[author]
name            = "Carter S. Levinson"
homepage        = "carterlevinson.net"

[extra]
sleek_author    = "John Q. Example"
sleek_abbr      = "JQE"
sleek_quote     = "You get what you pay for!"

sleek_copyright = "All rights reserved."
sleek_mathjax   = true

sleek_icon      = "images/icon.ico"
sleek_logo      = "images/logo.jpg"
sleek_image     = "images/image.jpg"

sleek_navbar    = [
  { link        = "/",           name = "Home" },
  { link        = "/blog",       name = "Blog" },
  { link        = "/tags",       name = "Tags" },
  { link        = "/categories", name = "Categories" },
  { link        = "/tags",       name = "Tags" },
  { link        = "/about",      name = "About"}
]

sleek_pages     = [
  { name        = "twitter", link = "https://twitter.com" },
  { name        = "github",  link = "https://github.com" },
  { name        = "email",   link = "mailto:author@domain.com" }
]
